### ISSUE TITLE
Complete Open Source Checklist

### ISSUE THREAD

**Issue by gautamarora** [CondeNast/launch-vehicle-fbm#85]
This is a master issue to work through the Condé Nast Open Source Checklist.

### Documentation
- [x] README
- [ ] CONTRIBUTING
- [ ] CODE_OF_CONDUCT
- [x] LICENSE
- [ ] ISSUE_TEMPLATE
- [x] PULL_REQUEST_TEMPLATE
- [x] CHANGELOG
- [x] [Announcement Blog Post](https://technology.condenast.com/story/bot-building-with-launch-vehicle-fbm)

### Development
- [x] Tests
- [x] Linter
- [ ] Travis
- [ ] Examples
- [x] Clear Github History

### README Checklist
- [x] Title
- [ ] Badges 
- [x] Description
- [ ] Prerequisite for using software ( if any )
- [ ] Install
- [x] Example Usage
- [x] Screenshots and GIFs
- [ ] Contributors
- [ ] Conde Nast Technology Logo
- [ ] Attributions ( mention 3rd party libs used etc. )
- [ ] Benchmarks (if any)
- [x] Prior Art (if any)

### Badges Checklist:
- [ ] License Badge
- [ ] Testing Badge
- [ ] CI Badge

**Comment by stripethree** [comment]
For the purposes of an _Announcement Blog Post_, I think we can suffice with [this post(https://technology.condenast.com/story/bot-building-with-launch-vehicle-fbm).

I am also checking off _Screenshots and GIFs_ as that is difficult to apply to an SDK. There are applicable screen shots in the blog post, but those do not seem appropriate to include in the `README`.

**Comment by stripethree** [comment]
In looking into this and chatting with @gautamarora, the original issue content is out of date. I installed and ran @gautamarora's [`opensource-check` tool] and here are the results on the current `master` branch (with some of the details clipped for brevity).

I ran the command without the `--org` argument since at the time we released `launch-vehicle-fbm` as open source, the guidance was to omit the `@condenast` organization name from the package. There is little value in unpublishing and republishing the package, so we'll stick with that scheme.

```shell
➜  ~ opensource-check --path Work/launch-vehicle-fbm
 PASS  Work/opensource-check/__checks__/dev.test.js
  Development
    ✓ should have a package.json (5ms)
    ✓ should have a .gitignore
    ✓ should have a Linter
    ✓ should have Tests (1ms)
    package.json
      ✓ should have the org namespace, if applicable
      ✓ should have a version (1ms)
      ✓ should have a description
      ✓ should have a main or bin (1ms)
      ✓ should have a repository (1ms)
      ✓ should have contributors
      ✓ should have a license

 FAIL  Work/opensource-check/__checks__/docs.test.js
  Documentation
    ✓ should have a Readme (2ms)
    ✓ should have a License (1ms)
    ✕ should have a Code of Conduct (15ms)
    ✕ should have Contributing Guidelines (3ms)
    ✕ should have an Issue Template (2ms)
    ✓ should have a Pull Request Template
    ✓ should have a Changelog (1ms)
    ✓ should have Examples
    Readme
      ✕ Should have Package Name as Title (1ms)
      ✕ should have an Install section (1ms)
      ✕ should have a Usage section (1ms)
Test Suites: 1 failed, 1 passed, 2 total
Tests:       6 failed, 16 passed, 22 total
Snapshots:   0 total
Time:        0.544s, estimated 1s
Ran all test suites.
➜  ~ opensource-check --p
